// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNdMyQUCcRS69-KEDT_a1_pVjQ0rYIpZ8',
    appId: '1:311589018533:web:e4a06929fda53f3817e64c',
    messagingSenderId: '311589018533',
    projectId: 'noteapp-45fd8',
    authDomain: 'noteapp-45fd8.firebaseapp.com',
    storageBucket: 'noteapp-45fd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANYgWXp0IQx-z6dF9_E5Wq6j140kvEtAg',
    appId: '1:311589018533:android:fcdbd1dbe4bbae4a17e64c',
    messagingSenderId: '311589018533',
    projectId: 'noteapp-45fd8',
    storageBucket: 'noteapp-45fd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMTl-ut77PbawTCmFsrJudjHPzlhI27so',
    appId: '1:311589018533:ios:e93a852c771b50dd17e64c',
    messagingSenderId: '311589018533',
    projectId: 'noteapp-45fd8',
    storageBucket: 'noteapp-45fd8.appspot.com',
    iosClientId: '311589018533-v0o42km1953mk31m9e6216m56g70t3ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMTl-ut77PbawTCmFsrJudjHPzlhI27so',
    appId: '1:311589018533:ios:cbf08ef750a6d32217e64c',
    messagingSenderId: '311589018533',
    projectId: 'noteapp-45fd8',
    storageBucket: 'noteapp-45fd8.appspot.com',
    iosClientId: '311589018533-ce5m8m2j216c6t7h8ouhs336271dat7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteapp.RunnerTests',
  );
}
